library 'ctc-encryption@shared-library'

pipeline {
  agent any
  triggers {
    eventTrigger jmespathQuery("jobType=='encrypted'")
  }
  stages {
    stage("Decrypt message") {
      when {
        triggeredBy "EventTriggerCause"
      }
      environment {
        PRIVATE_KEY = credentials("${env.SOURCE_JOB}")
      }
      steps {
        decryptSecureEvent("${env.PRIVATE_KEY}")
      }
    }
  }
}