library 'ctc-encryption@main'

pipeline {
  agent any
  triggers {
    eventTrigger jmespathQuery("jobType=='encrypted'")
  }
  stages {
    stage("Decrypt message") {
      when {
        triggeredBy "EventTriggerCause"
        expression {
          checkAllowList()
        }
      }
      steps {
        decryptSecureEvent()
      }
    }
  }
}