library 'ctc-encryption@main'

pipeline {
  agent any
  environment {
    PUBLIC_KEY = credentials("publicKey")
  }
  parameters {
    password(name: 'SECRET_STRING', description: 'Secret string to pass to downstream job')
  }
  stages {
    stage ("Send encrypted message") {
      steps {
        // publishSecureEvent("${env.PUBLIC_KEY}", "${params.SECRET_STRING}")
        script {
          env.ENCRYPTED_TEXT = sh(script: "echo ${params.SECRET_STRING} | openssl rsautl -inkey $PUBLIC_KEY -pubin -encrypt | base64 -w 0",
                                  returnStdout: true).trim()
        }
        publishEvent event: jsonEvent("{'jobType':'encrypted', 'encryptedText': '${env.ENCRYPTED_TEXT}'}"), verbose: true
      }
    }
  }
}