library 'ctc-encryption@main'

pipeline {
  agent any
  parameters {
    password(name: 'SECRET_STRING', description: 'Secret string to pass to downstream job')
  }
  stages {
    stage ("Send encrypted message") {
      steps {
        publishSecureEvent("publicKey", "${params.SECRET_STRING}")
      }
    }
  }
}